from __future__ import annotations

COLUMN_ALIASES = {
    "teams": {
        "team_id": ["team_id", "id", "teamid", "team_identifier"],
        "team_name": ["team_name", "name", "team", "full_name"],
        "abbreviation": ["abbreviation", "abbr", "team_abbreviation"],
        "city": ["city", "team_city"],
        "conference": ["conference"],
        "division": ["division"],
    },
    "players": {
        "player_id": ["player_id", "id", "playerid", "player_identifier"],
        "player_name": ["player_name", "name", "player", "full_name"],
        "first_name": ["first_name", "firstname"],
        "last_name": ["last_name", "lastname"],
        "position": ["position", "pos"],
    },
    "games": {
        "game_id": ["game_id", "id", "gameid"],
        "season_label": ["season_label", "season", "season_id"],
        "game_date": [
            "game_date",
            "date",
            "game_datetime",
            "game_day",
            "gameDateTimeEst",
        ],
        "game_type": ["game_type", "season_type", "type", "gameType"],
        "home_team_id": ["home_team_id", "home_team", "team_home_id", "home_id", "hometeamId"],
        "away_team_id": ["away_team_id", "away_team", "team_away_id", "away_id", "awayteamId"],
        "home_team_name": ["home_team_name", "hometeamName", "home_team"],
        "away_team_name": ["away_team_name", "awayteamName", "away_team"],
        "home_team_city": ["home_team_city", "hometeamCity"],
        "away_team_city": ["away_team_city", "awayteamCity"],
        "home_points": ["home_points", "pts_home", "home_score", "home_pts", "homeScore"],
        "away_points": ["away_points", "pts_away", "away_score", "away_pts", "awayScore"],
        "winner_team_id": ["winner_team_id", "winner_team", "winning_team_id", "winner"],
    },
    "player_game_stats": {
        "game_id": ["game_id", "id", "gameid"],
        "player_id": ["player_id", "id_player", "playerid", "personId"],
        "player_name": ["player_name", "player", "name"],
        "first_name": ["first_name", "firstname", "firstName"],
        "last_name": ["last_name", "lastname", "lastName"],
        "team_id": ["team_id", "team", "teamid", "playerteamId"],
        "player_team_name": ["playerteamName", "player_team_name"],
        "player_team_city": ["playerteamCity", "player_team_city"],
        "is_home": ["home", "is_home"],
        "starter": ["starter", "is_starter"],
        "minutes": ["minutes", "min", "mins", "numMinutes"],
        "points": ["points", "pts"],
        "rebounds": ["rebounds", "reb", "trb", "reboundsTotal"],
        "assists": ["assists", "ast"],
        "steals": ["steals", "stl"],
        "blocks": ["blocks", "blk"],
        "turnovers": ["turnovers", "tov"],
        "fouls": ["fouls", "pf", "personal_fouls", "foulsPersonal"],
        "plus_minus": ["plus_minus", "plusminus", "+/-", "plusMinusPoints"],
        "fg_made": ["fg_made", "fgm", "fieldGoalsMade"],
        "fg_attempts": ["fg_attempts", "fga", "fieldGoalsAttempted"],
        "three_made": ["three_made", "fg3m", "3pm", "threePointersMade"],
        "three_attempts": ["three_attempts", "fg3a", "3pa", "threePointersAttempted"],
        "ft_made": ["ft_made", "ftm", "freeThrowsMade"],
        "ft_attempts": ["ft_attempts", "fta", "freeThrowsAttempted"],
        "offensive_rebounds": ["offensive_rebounds", "oreb", "reboundsOffensive"],
        "defensive_rebounds": ["defensive_rebounds", "dreb", "reboundsDefensive"],
    },
}
