from __future__ import annotations

COLUMN_ALIASES = {
    "teams": {
        "team_id": ["team_id", "id", "teamid", "team_identifier"],
        "team_name": ["team_name", "name", "team", "full_name"],
        "abbreviation": ["abbreviation", "abbr", "team_abbreviation"],
        "city": ["city", "team_city"],
        "conference": ["conference"],
        "division": ["division"],
    },
    "players": {
        "player_id": ["player_id", "id", "playerid", "player_identifier"],
        "player_name": ["player_name", "name", "player", "full_name"],
        "first_name": ["first_name", "firstname"],
        "last_name": ["last_name", "lastname"],
        "position": ["position", "pos"],
    },
    "games": {
        "game_id": ["game_id", "id", "gameid"],
        "season_label": ["season_label", "season", "season_id"],
        "game_date": ["game_date", "date", "game_datetime", "game_day"],
        "game_type": ["game_type", "season_type", "type"],
        "home_team_id": ["home_team_id", "home_team", "team_home_id", "home_id"],
        "away_team_id": ["away_team_id", "away_team", "team_away_id", "away_id"],
        "home_points": ["home_points", "pts_home", "home_score", "home_pts"],
        "away_points": ["away_points", "pts_away", "away_score", "away_pts"],
        "winner_team_id": ["winner_team_id", "winner_team", "winning_team_id"],
    },
    "player_game_stats": {
        "game_id": ["game_id", "id", "gameid"],
        "player_id": ["player_id", "id_player", "playerid"],
        "player_name": ["player_name", "player", "name"],
        "team_id": ["team_id", "team", "teamid"],
        "starter": ["starter", "is_starter"],
        "minutes": ["minutes", "min", "mins"],
        "points": ["points", "pts"],
        "rebounds": ["rebounds", "reb", "trb"],
        "assists": ["assists", "ast"],
        "steals": ["steals", "stl"],
        "blocks": ["blocks", "blk"],
        "turnovers": ["turnovers", "tov"],
        "fouls": ["fouls", "pf", "personal_fouls"],
        "plus_minus": ["plus_minus", "plusminus", "+/-"],
        "fg_made": ["fg_made", "fgm"],
        "fg_attempts": ["fg_attempts", "fga"],
        "three_made": ["three_made", "fg3m", "3pm"],
        "three_attempts": ["three_attempts", "fg3a", "3pa"],
        "ft_made": ["ft_made", "ftm"],
        "ft_attempts": ["ft_attempts", "fta"],
        "offensive_rebounds": ["offensive_rebounds", "oreb"],
        "defensive_rebounds": ["defensive_rebounds", "dreb"],
    },
}
